services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_web
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/azureuser/certbot/etc:/etc/letsencrypt
      - /home/azureuser/certbot/www:/var/www/certbot
    environment:
      DOMAIN_NAME: immersive-analytics-for-energy-grid-data.uksouth.cloudapp.azure.com
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/azureuser/certbot/etc:/etc/letsencrypt
      - /home/azureuser/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ucabpc5@ucl.ac.uk --agree-tos --no-eff-email -d immersive-analytics-for-energy-grid-data.uksouth.cloudapp.azure.com

volumes:
  postgres_data:


